{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobmp-arango
  namespace: {{ .Release.Namespace }}
  labels:
    app: gobmp-arango
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gobmp-arango
  template:
    metadata:
      labels:
        app: gobmp-arango
    spec:
      containers:
      - name: gobmp-arango
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
        args:
        - --v
        - {{ .Values.verbosity | quote }}
        - --message-server
        - {{ .Values.global.kafka.server | quote }}
        - --database-server
        - {{ .Values.global.arangodb.server | quote }}
        - --database-name
        - {{ .Values.global.arangodb.databaseName | quote }}
        - --notify-event
        - {{ .Values.notifyEvent | quote }}
        volumeMounts:
        - name: credentials
          mountPath: /credentials
      volumes:
      - name: credentials
        secret:
          secretName: {{ .Release.Name }}-jalapeno
{{- end }}
