apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jalapeno.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
type: Opaque
data:
  .username: {{ .Values.global.credentials.arangoUsername | b64enc | quote }}
  .password: {{ .Values.global.credentials.arangoPassword | b64enc | quote }}
